service: smart-home-layer

provider:
  name: aws
  runtime: provided.al2023
  region: ${opt:region, 'eu-central-1'}

layer:
  name: SmartHomeLayer
  path: ./go
  compatibleRuntimes:
    - provided.al2023

resources:
  DeviceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  DeviceQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: deviceQueue

  Outputs:
    CommonLambdaLayer:
      Description: "The ARN of the Common Lambda Layer"
      Value:
        Ref: Common

    DeviceTableName:
      Description: "The name of the DynamoDB table"
      Value:
        Ref: DeviceTable

    DeviceQueueURL:
      Description: "The URL of the SQS queue"
      Value:
        Ref: DeviceQueue

    DeviceQueueARN:
      Description: "The ARN of the SQS queue"
      Value:
        Fn::GetAtt:
          - DeviceQueue
          - Arn
