org: doodoodynamics
service: smart-home

provider:
  name: aws
  runtime: provided.al2023
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  profile: default
  architecture: arm64

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt:
            - DeviceTable
            - Arn
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
      Resource:
        - Fn::GetAtt:
            - DeviceQueue
            - Arn

package:
  individually: true

functions:
  createDevice:
    handler: handlers/createDevice/main
    package:
      artifact: handlers/createDevice/main/create_device.zip
    events:
      - http:
          path: devices
          method: post

  getDevice:
    handler: handlers/getDevice/bootstrap
    package:
      artifact: handlers/getDevice/main/get_device.zip
    events:
      - http:
          path: devices/{id}
          method: get

  updateDevice:
    handler: handlers/updateDevice/bootstrap
    package:
      artifact: handlers/updateDevice/main/update_device.zip
    events:
      - http:
          path: devices/{id}
          method: put

  deleteDevice:
    handler: handlers/deleteDevice/bootstrap
    package:
      artifact: handlers/deleteDevice/main/delete_device.zip
    events:
      - http:
          path: devices/{id}
          method: delete

  processSQSMessage:
    handler: handlers/processSqs/bootstrap
    package:
      artifact: handlers/processSqs/main/process_sqs.zip
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - DeviceQueue
              - Arn

resources:
  Resources:
    DeviceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: devices
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    DeviceQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: deviceQueue

  Outputs:
    DeviceTableName:
      Description: "The name of the DynamoDB table"
      Value:
        Ref: DeviceTable

    DeviceQueueURL:
      Description: "The URL of the SQS queue"
      Value:
        Ref: DeviceQueue

    DeviceQueueARN:
      Description: "The ARN of the SQS queue"
      Value:
        Fn::GetAtt:
          - DeviceQueue
          - Arn
