service: smart-home

provider:
  name: aws
  runtime: provided.al2023
  region: us-west-2
  environment:
    AWS_REGION: ${self:provider.region}
    DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
    SQS_QUEUE_URL: ${self:provider.environment.SQS_QUEUE_URL}

functions:
  createDevice:
    handler: main
    events:
      - http:
          path: devices
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - Fn::GetAtt:
              - DeviceTable
              - Arn

  getDevice:
    handler: main
    events:
      - http:
          path: devices/{id}
          method: get
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource:
          - Fn::GetAtt:
              - DeviceTable
              - Arn

  updateDevice:
    handler: main
    events:
      - http:
          path: devices/{id}
          method: put
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          - Fn::GetAtt:
              - DeviceTable
              - Arn

  deleteDevice:
    handler: main
    events:
      - http:
          path: devices/{id}
          method: delete
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource:
          - Fn::GetAtt:
              - DeviceTable
              - Arn

  processSQSMessage:
    handler: main
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - DeviceQueue
              - Arn
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - sqs:ReceiveMessage
          - sqs:DeleteMessage
        Resource:
          - Fn::GetAtt:
              - DeviceTable
              - Arn
          - Fn::GetAtt:
              - DeviceQueue
              - Arn

resources:
  DeviceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.DYNAMODB_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  DeviceQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: deviceQueue

  Outputs:
    DeviceTableName:
      Description: "The name of the DynamoDB table"
      Value:
        Ref: DeviceTable

    DeviceQueueURL:
      Description: "The URL of the SQS queue"
      Value:
        Ref: DeviceQueue

    DeviceQueueARN:
      Description: "The ARN of the SQS queue"
      Value:
        Fn::GetAtt:
          - DeviceQueue
          - Arn
