service: create-device

provider:
  name: aws
  runtime: provided.al2023
  region: ${opt:region, 'eu-central-1'}

functions:
  createDevice:
    handler: cmd/createDevice/main
    layers:
      - { Ref: SmartHomeLambdaLayer }
    events:
      - http:
          path: devices
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - Fn::GetAtt:
              - DeviceTable
              - Arn

layers:
  SmartHomeLambdaLayer:
    Ref: SmartHomeLambdaLayer
