service: create-device

provider:
  name: aws
  runtime: provided.al2023
  region: ${opt:region, 'eu-central-1'}

functions:
  processSQSMessage:
    handler: cmd/processSqs/main
    layers:
      - { Ref: SmartHomeLambdaLayer }
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - DeviceQueue
              - Arn
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - sqs:ReceiveMessage
          - sqs:DeleteMessage
        Resource:
          - Fn::GetAtt:
              - DeviceTable
              - Arn
          - Fn::GetAtt:
              - DeviceQueue
              - Arn
layers:
  SmartHomeLambdaLayer:
    Ref: SmartHomeLambdaLayer
