service: create-device

provider:
  name: aws
  runtime: provided.al2023
  region: ${opt:region, 'eu-central-1'}

functions:
  deleteDevice:
    handler: cmd/deleteDevice/main
    layers:
      - { Ref: SmartHomeLambdaLayer }
    events:
      - http:
          path: devices/{id}
          method: delete
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource:
          - Fn::GetAtt:
              - DeviceTable
              - Arn

layers:
  SmartHomeLambdaLayer:
    Ref: SmartHomeLambdaLayer
