service: create-device

provider:
  name: aws
  runtime: provided.al2023
  region: ${opt:region, 'eu-central-1'}

functions:
  getDevice:
    handler: cmd/getDevice/main
    layers:
      - { Ref: SmartHomeLambdaLayer }
    events:
      - http:
          path: devices/{id}
          method: get
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource:
          - Fn::GetAtt:
              - DeviceTable
              - Arn

layers:
  SmartHomeLambdaLayer:
    Ref: SmartHomeLambdaLayer
